sphereon:
  cas:
    did:
      auth:
        appId: AlfrescoIntegration
        appDid: did:ethr:0x88ed694ffe9244e2993d2932638a5c736371fc04
        didMapUrl: http://castestsetup-fbe9303b7a6cbee1.elb.eu-west-1.amazonaws.com:8080
        didTransportsUrl: http://castestsetup-fbe9303b7a6cbee1.elb.eu-west-1.amazonaws.com:3000
        appSecret: 2106b0925c0b7486d3474ea0521f0a8750992902c7a13f02498e4066da3cf0f0
        baseCasUrl: https://alfresco.dev.sphereon.com:8443/cas
