sphereon:
  cas:
    did:
      auth:
        appId: <insert-app-id>
        appDid: <insert-app-did>
        didMapUrl: <insert-did-mapping-url>
        didTransportsUrl: <insert-did-transports-url>
        appSecret: <insert-app-secret>
        baseCasUrl: <insert-base-cas-url>
